name: Release Workflow

sharedSchemes:
  - SOAPFT

environment:
  xcode: latest

actions:
  - name: Generate Tuist Project
    script: |
      brew install tuist
      tuist generate || exit 1

  - name: Build and Test
    build:
      workspace: SOAPFT.xcworkspace
      scheme: SOAPFT
      destination:
        platform: iOS
        name: iPhone 15
    test:
      testPlan: Default

postActions:
  - name: Upload to TestFlight
    uploadToTestFlight:
      distributionGroups:
        - Internal Testers
