default_platform(:ios)

platform :ios do
  lane :beta do
    if ENV["CI"]
      create_keychain(
        name: "ci.keychain",
        password: "ci_password",
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        add_to_search_list: true
      )
      ENV["MATCH_KEYCHAIN_NAME"] = "ci.keychain"
      ENV["MATCH_KEYCHAIN_PASSWORD"] = "ci_password"
    end

    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_API_KEY']
    )

    match(
      type: "development", # TestFlight용 인증서
      readonly: false,
      git_url: ENV['MATCH_REPO_URL'],
      api_key: api_key,
      force: true
    )

    build_app(
      scheme: "SOAPFT",
      configuration: "Debug", # match type과 맞춰야 함
      export_method: "development",
      export_options: {
        provisioningProfiles: {
          "io.tuist.SOAPFT" => "match Development io.tuist.SOAPFT"
        }
      }
    )

    deliver(
      api_key: api_key,
      submit_for_review: false,
      skip_metadata: true,
      skip_screenshots: true
    )
  end
end
