platform :ios do
  lane :beta do
    if ENV["CI"]
      create_keychain(
        name: "ci.keychain",
        password: "ci_password",
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        add_to_search_list: true
      )
      ENV["MATCH_KEYCHAIN_NAME"] = "ci.keychain"
      ENV["MATCH_KEYCHAIN_PASSWORD"] = "ci_password"

      match(
        type: "appstore",
        readonly: false,
        git_url: "https://#{ENV['USERNAME']}:#{ENV['PAT_TOKEN']}@github.com/SOAPFT/SOAPFT-iOS-certificates"
      )
    else
      # 로컬 테스트용: 로컬 키체인 인증서를 쓸 수 있게 설정하거나 생략
      match(
        type: "appstore",
        readonly: false
      )
    end

    build_app(scheme: "SOAPFT")
  end
end
